services:
  stalwart:
    image: stalwartlabs/stalwart:v0.16
    container_name: mailserver
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "127.0.0.1:10025:25"
      - "127.0.0.1:10465:465"
      - "127.0.0.1:10993:993"
      - "127.0.0.1:10443:443"
      - "127.0.0.1:18080:8080"
    volumes:
      - etc:/etc/stalwart
      - data:/var/lib/stalwart

volumes:
  etc:
  data:
